{% set name = "tbot" %}
{% set version = "0.9.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Rahix/tbot/archive/v{{ version }}.tar.gz
  sha256: ce9b73c43c594934a4b0bafb0f08faa03c29c2f4454da4b72b96e6b522a076d6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - paramiko
    - termcolor2

test:
  imports:
    - tbot
    - tbot.tc
    - tbot_contrib
    - tbot_contrib.connector
    - tbot_contrib.swupdate
    - tbot_contrib.timing

about:
  home: https://github.com/Rahix/tbot
  summary: Automation/Testing tool for Embedded Linux Development
  license: GPL-2.0-or-later
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - saibhargav1508
