{% set name = "tbot" %}
{% set version = "0.8.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Rahix/tbot/archive/v{{ version }}.tar.gz
  sha256: 6cf068d90e061f961e6e3ae4625ace4f5820d9865804efe0e806d6857b7333ea

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - paramiko
    - termcolor2

test:
  imports:
    - tbot
    - tbot.tc
    - tbot_contrib
    - tbot_contrib.connector
    - tbot_contrib.swupdate
    - tbot_contrib.timing

about:
  home: https://github.com/Rahix/tbot
  summary: Automation/Testing tool for Embedded Linux Development
  license: GPL-2.0-or-later
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - saibhargav1508
