{% set name = "tbot" %}
{% set version = "0.9.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Rahix/tbot/archive/v{{ version }}.tar.gz
  sha256: 822c959227204934b4c572ccbdc3bd20ddd1bb1cec8b7a1635e7ce85a6734a05

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - paramiko
    - termcolor2

test:
  imports:
    - tbot
    - tbot.tc
    - tbot_contrib
    - tbot_contrib.connector
    - tbot_contrib.swupdate
    - tbot_contrib.timing

about:
  home: https://github.com/Rahix/tbot
  summary: Automation/Testing tool for Embedded Linux Development
  license: GPL-2.0-or-later
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - saibhargav1508
